### ISSUE TITLE
Inaccurate sample code in documentation for CodeGenerator.ForEach

### ISSUE THREAD

**Issue by scharnyw** [sakno/dotNext#19]
This is a minor documentation issue.

According to the [docs](https://sakno.github.io/dotNext/features/metaprogramming/loop.html#foreach-loop), `CodeGenerator.ForEach` can be used as follows:

```
Lambda<Action<string>>(fun => 
{
    ForEach(fun[0], ch =>
    {
        WriteLine(ch);
    });
});
```

But this code throws `System.ArgumentException` because `CodeGenerator.WriteLine` does not work for `System.Char`. In fact it appears it doesn't work for any primitive value type. Perhaps I can just update the docs from `string` to `List<string>` instead?

**Comment by sakno** [comment]
@scharnyw , unfortunately it's a bug in ` WriteLine` expression implementation. It was designed to accept value of any type. If you want to contribute then check `WriteLineExpression.WriteLineTo` private method. The bug is there.
As a workaround, you can use `AsString()` extension method that allows to construct `x.ToString()` expression:
```csharp
Lambda<Action<string>>(fun => 
{
    ForEach(fun[0], ch =>
    {
        WriteLine(ch.AsString());
    });
});
```

**Comment by scharnyw** [comment]
Ah, I see where the issue originates from. I'll submit a fix when I get around to it. Thanks for the quick confirmation!

**Comment by sakno** [comment]
@scharnyw , unfortunately merged PR still not working for some cases. See dotnet/runtime#44377

**Comment by scharnyw** [comment]
@sakno Thanks for investigating and fixing all the cases! Sorry I had been away over the weekends.
