### ISSUE TITLE
Compile time codegen?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [sakno/DotNext#2]
Via https://github.com/ltrzesniewski/InlineIL.Fody/issues/6 ? 
Or msbuild task with roslyn code generator?

**Comment by sakno** [comment]
Gist with proposal was created to continue discussion in task [Type Classes](https://github.com/dotnet/csharplang/issues/110) and it is not directly related to DotNext.Reflection library. It was specified as a proof of concept that type classes can be introduced into language without CLR modifications because the library already contains support of concept types based on mix of reflection (for binding) and delegates (for method calls). The LDM team responsible for Roslyn compiler offers different implementation of concept types using witness structures. 

The current implementation of concept types in .NEXT based on invocation of delegates which have equal performance to _calli_ instruction or direct method call. Look at the [benchmarks](https://sakno.github.io/DotNext/benchmarks.html#strongly-typed-reflection). Therefore, I don't see any reasons to use InlineIL library and replace delegate invocation with _calli_ instruction.
