### ISSUE TITLE
Possible race condition between snapshot and logentry

### ISSUE THREAD

**Issue by natilivni** [sakno/dotNext#42]
Hello, I am seeing a strange behavior.  My state (and therefore my snapshot) is a dictionary object.  The last logentry before a snapshot builder is requested enters a particular key into the dictionary.  The snapshotbuilder then creates a snapshot with the entire dictionary.

Now, when I bring down the nodes and bring them up again, a replay occurs in which the snapshot is (obviously) applied first, but then the logentry which was seen previous to the building of the snapshot is applied after which causes a duplicate key exception.  It seems as if this is a race condition between the last entry before the snapshot and the snapshot record itself.

Any ideas?

**Comment by sakno** [comment]
I need repro code. If this is happening constantly then it doesn't look like a race condition. All writes to the persistent WAL are protected by write lock. You need to check the logic of your app more closely because this persistent WAL is actively using in production. Additionally, you can try to reproduce the issue using `RaftNode` example.

All compacted log entries during snapshot building are deleted. To be more precise, they are deleted with the containing partition. Partition is a file with the log entries. You can stop your node, create your persistence engine and examine the snapshot and committed log entries with their terms using public methods of `PersistentState` class.

**Comment by sakno** [comment]
@natilivni , if you trying to implement distributed lock service then take a look at the commit 7d4f7b374905a3de04f213e11e3138e20b847f06. It was successful attempt to implement working prototype. But it was abandoned afterwards because I was not ready to support the implementation and many architectural decisions were not perfect.

**Comment by sakno** [comment]
For diagnostics purposes, compare `Timestamp` of the snapshot with the timestamp of this problematic log entry. If the timestamp of the log entry is greater than the timestamp of the snapshot then extra log entry caused by application logic.

**Comment by natilivni** [comment]
I found something interesting.  When the logentry is applied before compaction occurs, its timestamp is fully formed:
```
Process LogEntry. Term: 3, Length: 49, Timestamp: 08:42:43.92048, IsSnapshot: False, Creating Lock. LockId: 66f3b191-62a3-4841-bb46-2ffbfa19123b
Writing new snapshot entry. Timestamp: 08:42:43.97316, Snapshot: ... "Id":"66f3b191-62a3-4841-bb46-2ffbfa19123b" ...
```

When the replay occurs, the millisecond information is stripped and I see the following:
```
Snapshot message read. Term: 3, Length: 2565, Timestamp: 08:42:44.22174, IsSnapshot: True, Snapshot: ... "Id":"66f3b191-62a3-4841-bb46-2ffbfa19123b" ...
Process LogEntry. Term: 3, Length: 49, Timestamp: 08:42:43, IsSnapshot: False. LockId: 66f3b191-62a3-4841-bb46-2ffbfa19123b
```

It looks like the millisecond information was not persisted for **Timestamp: 08:42:43**.  And the log entry that should have been compacted is definitely replaying on startup.  I will try to get a sample project that reproduces this...

**Comment by sakno** [comment]
Stripping is a result of passing `Timestamp` in RFC1123-compliant format through the wire.

**Comment by natilivni** [comment]
Attached is a sample solution that demonstrated the issue.  To reproduce:

Start the solution with multiple startup projects so that Node1,Node2,Node3 are the startup projects.
After leader is established, use swagger to add guids to the dictionary.  Do this until compaction occurs (I set the partition size to 10).
After this stop the run.
restart the run.  Now, when the replay occurs, the snapshot is run before the last applied entry that was before the snapshow.

[Issue42.zip](https://github.com/sakno/dotNext/files/5761559/Issue42.zip)

**Comment by sakno** [comment]
The following code is incorrect because the result of `WriteAsync` is not awaited.
```csharp
protected override void WriteSnapshotAsync<TWriter>(TWriter writer, CancellationToken token)
        {
            var snapshotJson = GetSnapshot();
            
            _logger.LogInformation("Writing new snapshot entry. SnapshotJson: {SnapshotJson}", snapshotJson);

            writer.WriteAsync(snapshotJson.AsMemory(), _encoding, _stringLengthEncoding, token);
        }
```

**Comment by natilivni** [comment]
Good catch, but when I change that line to:
` writer.WriteAsync(snapshotJson.AsMemory(), _encoding, _stringLengthEncoding, token).AsTask().Wait();`

The problem still persists.

**Comment by sakno** [comment]
As stated previously, the problem is not in `PersistentState` implementation. It's invalid to serialize snapshot in the way how you doing this in your project. Actually, the first partition (with index `0`) containing the first ephemeral log entry at index 0 which is always committed. Therefore, the snapshot is creating for the first 9 Guids, not for 10. But your logic assumes that the snapshot is the entire state of the engine. As a result, tenth log entry is added to the next partition which is not included in the snapshot and replayed on startup separately from the snapshot.

Your current state in the memory is not the same as the snapshot log entry. You current state _can be_ reconstructed incrementally from the snapshot and unsquashed entities.

**Comment by natilivni** [comment]
Thank you for the clarification.  I think I was thrown off by your response in #40 (https://github.com/sakno/dotNext/discussions/40#discussioncomment-255248).  I will reconstruct the snapshot completely and hopefully that will work.

**Comment by sakno** [comment]
@natilivni , are you using `GetAwaiter().GetResult()` just for debugging purposes? Also, I saw that you use `10_000` as a partition size. I think this value is too big and will cause performance issues on snapshotting. Compaction of thousands of log entries is not the fast operation.

**Comment by natilivni** [comment]
Yes, the GetAwaiter is just to get everything working. I will do a proper cleanup later. I have not yet thought of an appropriate partition size though. I was guessing 10,000 is too large. Do you have a good method of estimating an appropriate partition size?

**Comment by sakno** [comment]
Only run the benchmarks. In your situation I would recommend to use ~10. Additionally, it's recommended to configure `InitialPartitionSize` parameter declared in `PersistentState.Options` to pre-allocate the partition file on the and make contiguous which usually dramatically improves I/O performance because the file is not fragmented on the file system.
