### ISSUE TITLE
 How to use raft to build a kv system？

### ISSUE THREAD

**Issue by squarezx** [sakno/dotNext#5]
Thank you very much for providing a raft C # implementation. I now want to build a distributed kv system. Can I use your framework to achieve this?

**Comment by sakno** [comment]
You're welcome, @squarezx! In your case Raft in just a beginning of the way. 
**Part 1: Database backend**
1. You need `DotNext.AspNetCore.Cluster` dependency from NuGet. It is required because it contains implementation of HTTP-based communication between Raft nodes on top of ASP.NET Core infrastructure with all its benefits: DI, logging etc. However, you're able to provide your own network transport (e.g. TCP) without this library. In this case you need `DotNext.Net.Cluster` library and [RaftCluster](https://sakno.github.io/dotNext/api/DotNext.Net.Cluster.Consensus.Raft.RaftCluster-1.html) class from it. This class provides transport-agnosic implementation of Raft and actively used by HTTP-specific implementation from `DotNext.AspNetCore.Cluster` library. But I think that HTTP is OK for you because this implementation supports HTTP 1 and 2 as well as SSL and other things.
1. Any reliable database engine constructed on top .NEXT framework should use persistent Write Ahead Log. You're luck and it is shipped with library. Read [this](https://sakno.github.io/dotNext/features/cluster/wal.html) article carefully.
1. Now you have two key components for your K/V database. However, some level of customization is required. You need to derive from [PersistentState](https://sakno.github.io/dotNext/api/DotNext.Net.Cluster.Consensus.Raft.PersistentState.html) and override `CreateSnapshot` method as described in the article above. This method is responsible for reducing size of Write Ahead Log through comnination of log entries into single one. This process called _Snapshotting_. I hope you're aware about Write Ahead Log role in database engines. If not then this is different thread for discussion.
 1. The next important method is `ApplyAsync` which is virtual by default and do nothing. In your derived class this method should be responsible for decoding command for K/V database from log entry. Decoded command can be applied to underlying K/V database engine to reflect all necessary changes (CRUD operations). Here you need to design your own binary format for each command. [LogEntry](https://sakno.github.io/dotNext/api/DotNext.Net.Cluster.Consensus.Raft.PersistentState.LogEntry.html) value type contains all necessary methods for decoding binary data in stream-like format with low overhead. `CreateSnapshot` and `ApplyAsync` methods are called automatically in synchronized context so you don't need to care about concurrency.
1. Now you need to design K/V engine which can handle commands decoded from log entries and maintain K/V storage on disk. Let's assume that your engine can be described by interface `IKeyValueDatabaseEngine` and appropriate implementation.
1. Parameter of type `IKeyValueDatabaseEngine` should be added to constructor of your type derived from `PersistentState`. This approach allows to inject database engine using DI. Of course, you need to write implementation of `IKeyValueDatabaseEngine` interface and register it as singleton in DI container.

Now the backend for K/V database in finished. However, we need a fronted in the form of REST API which allows clients to operate with this database.
**Part 2: Database frontend**
1. Design your REST API. Read operations can be performed on every Raft node even if it is not a leader. Therefore, such API can call some methods from `IKeyValueDatabaseEngine` for reading data
1. All writes can be handled by leader node only. However, the request can be received by follower node due to load balancing and HTTP reverse proxy. Read [this](https://sakno.github.io/dotNext/features/cluster/aspnetcore.html#redirection-to-leader) chapter carefully to solve this issue using automatic routing to leader node.
1. Every write produces a set of changes. The changeset can be represented in the form of log entries. These log entries should be submitted to Write Ahead Log and committed.
1. Use [IReplicatedCluster](https://sakno.github.io/dotNext/api/DotNext.Net.Cluster.Replication.IReplicationCluster-1.html) interface that can be injected using DI for writing changes into Write Ahead Log. You need to call `WriteAsync` method  with `WriteConcern.LeaderOnly` or `WriteConcern.None` depending on chosen [CAP](https://en.wikipedia.org/wiki/CAP_theorem) characteristics. 
1. `WriteAsync` will write uncommited entries into `PersistentState` and wait when all of them will be committed. When entries are marked as commited then `ApplyAsync` overridden method will be called automatically. Note that `WriteAsync` method cal be called by leader node only. However, automatic redirection helps you with that.

Additionally, you can examine [RaftNode](https://github.com/sakno/dotNext/tree/master/src/examples/RaftNode) example which demonstrates most of concepts described in this post.

**Comment by squarezx** [comment]
Thank you very much

**Comment by sakno** [comment]
@squarezx adoption for 2.0 is improved and published [here](https://sakno.github.io/dotNext/features/cluster/raft.html). I recommend you to use latest version of library because now you don't need to implement persistent state of your database. State reconstruction provided by persistent WAL implementation shipped with the library can do this for you.

**Comment by natilivni** [comment]
Hello, regarding the following:

"Use IReplicatedCluster interface that can be injected using DI for writing changes into Write Ahead Log. You need to call WriteAsync method" 

I can not find this method on the interface nor can I find an extension method for this. Has this been refactored since this issue? If so, what is the current correct way to initiate a write to the audit log?

**Comment by sakno** [comment]
@natilivni , correct. 2.x branch doesn't contain `WriteAsync` method of `IReplicationCluster` interface anymore. Could you please open a new topic on _Discussions_ tab.

**Comment by natilivni** [comment]
Done. Discussion #27
