### ISSUE TITLE
RaftCluster - AllowPartitioning option 

### ISSUE THREAD

**Issue by mjameson-se** [sakno/dotNext#58]
I'm trying to set up a system where things function more or less normally no matter how many members are online and no matter how many members are part of the cluster. Looking at the documentation I thought AllowPartitioning would provide that functionality, but it wasn't working and looking at the test cases (`SingleNodeWithoutConsensus`) it appears it isn't meant to work the way I want... but I'm a little bit confused about why the current behavior is desired. 

As best as I can tell, the only real reference to the option is when in the leader state, you won't bump out of leader state upon discovering that a quorum is not present. The state machine cannot make commits, and non-leaders will not become leaders.

I understand that strictly speaking Raft doesn't allow commits without consensus... so maybe what I want isn't really Raft, but it feels like what you've got is so close to being what I need. What do you think?

**Comment by sakno** [comment]
`AllowPartitioning` allows presence of nominal leader in the segment of the cluster in case of network partitioning. However, such a leader is not able to commit log entries because there is no response from the majority of cluster nodes. It means that if `AllowPartitioning=true` then _external observer_ in partitioned network can see multiple leaders. However, only one (or none) leader may commit log entries. This may be confusing for most developers. Therefore, `AllowPartitioning` is disabled by default. In this case, if leader cannot communicate with the majority of nodes, its state will be downgraded to follower state. Thus, external observer will see only one (or none) leader even in partitioned network.

> a system where things function more or less normally no matter how many members are online and no matter how many members are part of the cluster

What you mean by _normally_? It always depends on expected characteristics of you distributed system. [CAP theorem](https://en.wikipedia.org/wiki/CAP_theorem) is a good starting point in understanding of theoretical limits of distributed systems. In case of Raft you have the following limitations:
1. You cannot perform write operations without a leader, because...
2. only leader node can perform writes
3. If you need consistent reads (strict consistency model) then you need to read from leader node
4. If stale reads are OK (weak consistency model) then you can read from any node in the cluster. Weak consistency model is applicable for many applications such as distributed cache, K/V databases etc.

As a result, if weak consistency is your choice then cluster will be available for reads mostly in any bad situation even if each node isolated by network partitioning.

**Comment by sakno** [comment]
However, there is an option to increase consistency and availability of some data in Raft cluster. This is called _sharding_. There are some implementations of algorithm called Multi-Raft where each shard has its own leader. In case of failures some shards may be unavailable. However, if shard has functioning leader then you can perform writes of data belonging to this shard only.

At the moment, sharding is not provided out-of-the-box in my library. However, there is no limit to build sharded cluster on top of existing version.

**Comment by mjameson-se** [comment]
Alright, sounds like Raft is just not going to work for my use-case.
