### ISSUE TITLE
Sample for transport-agnostic DotNext.Net.Cluster package

### ISSUE THREAD

**Issue by IanElsinga** [sakno/dotNext#6]
Hi, 

I would like to implement a gRPC version of RaftCluster in the DotNext.Net.Cluster package.  However, I can't find any samples or detailed information on how to go about this.  I have looked at the HTTP version but it seems very different than the transport-agnostic implementation.  Do you have a working sample using RaftCluster? 

Thanks.

**Comment by sakno** [comment]
@IanElsinga , I was thinkg about gRPC implementation but I rejected this due to following reasons:
* Current implementation already has support of HTTP/2 and, as a result, multiplexed connection
* Log entries are transferred in binary form inside of request body. Moreover, multipart content writer is highly [optimized](https://github.com/sakno/dotNext/blob/master/src/cluster/DotNext.AspNetCore.Cluster/Net/Cluster/Consensus/Raft/Http/AppendEntriesMessage.cs#L188) and has near-zero memory pressure.
* gRPC uses textual headers as well as regular HTTP/REST application

The only place where you can gain in performance is the transfer of log entries. Currently, _AppendEntries_ request uses multipart content. This drawback can be solved with pure binary messages in gRPC. IMHO, pure TCP or QUIC implementation could be much valuable. Anyway, .NEXT is open-source and I will glad to help you in this journey.

At this moment I don't have public guide for this so I provide description here:
1. `RaftCluster<TMember>` is transport-agnostic implementation containing Raft logic only. You need to derive from this class
1. Your derived class must provide actual implementation of `TMember` generic parameter. Such class should contain all transport-specific logic for communication with cluster members. [RaftClusterMember](https://github.com/sakno/dotNext/blob/master/src/cluster/DotNext.AspNetCore.Cluster/Net/Cluster/Consensus/Raft/Http/RaftClusterMember.cs) represents HTTP-specific communication. `IRaftClusterMember` interface must be implemented properly and its methods are [self-documented](https://sakno.github.io/dotNext/api/DotNext.Net.Cluster.Consensus.Raft.IRaftClusterMember.html):
1.1. `NextIndex` property should return the location in the memory where index of next log entry is stored. No additional logic is needed.
1.2. `AppendEntriesAsync` method is responsible for sending _AppendEntries_ Raft message with log entries for replication
1.3. `CancelPendingRequests` to cancel outbound pending requests
1.4. `VotAsync` method is responsible for sending _Vote_ Raft message using during leader election
1.5. `InstallSnapshotAsync` method is responsible for WAL snapshot installation
1. Core logic of these methods already implemented in `RaftCluster` class so you need to provide transport-specific data conversion only.
1.1. [ReceiveEntries](https://sakno.github.io/dotNext/api/DotNext.Net.Cluster.Consensus.Raft.RaftCluster-1.html#DotNext_Net_Cluster_Consensus_Raft_RaftCluster_1_ReceiveEntries__1__0_System_Int64_ILogEntryProducer___0__System_Int64_System_Int64_System_Int64_) method should be called by receiver of _AppendEntries_ message sent by another node
1.2. [ReceiveSnapshot](https://sakno.github.io/dotNext/api/DotNext.Net.Cluster.Consensus.Raft.RaftCluster-1.html#DotNext_Net_Cluster_Consensus_Raft_RaftCluster_1_ReceiveSnapshot__0_System_Int64_DotNext_Net_Cluster_Consensus_Raft_IRaftLogEntry_System_Int64_) method should be called by receiver of  _InstallSnapshot_ message
1.3. [ReceiveVote](https://sakno.github.io/dotNext/api/DotNext.Net.Cluster.Consensus.Raft.RaftCluster-1.html#DotNext_Net_Cluster_Consensus_Raft_RaftCluster_1_ReceiveVote__0_System_Int64_System_Int64_System_Int64_) method should be called by receiver of _Vote_ message
1. `RaftCluster<TMember>.StartAsync` must be overridden to provide initialization logic such as opening the socket, self-announcement and discovery of other nodes over the network. 
1. `RaftCluster<TMember>.StopAsync` must be overridden to stop receiving messages through the network and closing the socket.

In other words, the class derived from `RaftCluster` contains logic of the receiver. The class implementing `IRaftClusterMember` contains logic of the sender. The existing implementation for ASP.NET Core is a good demonstration of this architecture:
* [Receiver](https://github.com/sakno/dotNext/blob/master/src/cluster/DotNext.AspNetCore.Cluster/Net/Cluster/Consensus/Raft/Http/RaftHttpCluster.Messaging.cs)
* [Sender](https://github.com/sakno/dotNext/blob/master/src/cluster/DotNext.AspNetCore.Cluster/Net/Cluster/Consensus/Raft/Http/RaftHttpCluster.Messaging.cs)

Optionally, you may want to implement additional cluster features such as general-purpose messaging and dynamic addition/removal of cluster members. All these features and related interfaces described [here](https://sakno.github.io/dotNext/features/cluster/index.html). For instance, existing implementation for ASP.NET Core supports all of these.

Hope that this information will be helpful for you.

**Comment by sakno** [comment]
UPD: I wrote the official guide for your situation. Please examine [this](https://sakno.github.io/dotNext/features/cluster/raft.html#guide-custom-transport) article.

**Comment by IanElsinga** [comment]
Thanks very much, @sakno !!  That's WAY more assistance than I expected.  My system already uses gRPC and not HTTP and they are windows services that don't use the ASP.NET Core framework.  That is why I feel there is a use case for that.   I am trying to create a distributed sequential sequence number generator (must be incremental integers, not time-based or UUIDs).  

Thanks again and I'll let you know how I get on with the gRPC implementation.

**Comment by sakno** [comment]
@IanElsinga , you don't need to work on gRPC anymore. The new release is almost done and will include TCP and UDP transport for Raft that are not dependent on ASP.NET Core. Read [here](https://sakno.github.io/dotNext/features/cluster/raft.html#network-transport) for more info.

**Comment by IanElsinga** [comment]
Thanks @sakno! Good news!
